### ISSUE TITLE
Multiple RTP connections support

### ISSUE THREAD

**Issue by MicheleLonghi** [dnadoba/MIDIKit#3]
Would be amazing to be able to create multiple MIDI network connections, aka use multiple RTP ports.
From my knowledge, there are two ways for doing that: 
1. Use of custom apple properties
2. Use the new APIs (I thing iOS 13/macOS 10.15 or later)

**Comment by dnadoba** [comment]
Never heard of RTP-MIDI but just read the Wikipedia article.
Looks like CoreMIDI should have support for it.

Nevertheless, I have implemented a subset of RTP in Swift: https://github.com/dnadoba/SwiftRTP
I use it to send and receive H264 for an App I currently write for my Bachelor Thesis.

**Comment by MicheleLonghi** [comment]
I close this issue since it's pretty easy now to initialize the MIDIClient with Network Connection from my last commit (see Pull Request from my forked repo). To support multiple connections, all it needs is to instantiate one client for each connection.
Cheers.
